//products
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const PRODUCTS_FETCHING = 'PRODUCTS_FETCHING'
export const CHANGE_PRODUCT_COLOR = 'CHANGE_PRODUCT_COLOR'
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE'
export const SET_TOTAL_PRODUCTS = 'SET_TOTAL_PRODUCTS'

//cart
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART'
export const TOGGLE_CART_MODAL = 'TOGGLE_CART_MODAL'
export const TOGGLE_ORDER_FIELD = 'TOGGLE_ORDER_FIELD'

//order
export const POST_ORDER_DATA = 'POST_ORDER_DATA'
export const TOGGLE_ORDER_COMPLETED = 'TOGGLE_ORDER_COMPLETED'